### ISSUE TITLE
Can't install operator on a specific namespace

### ISSUE THREAD

**Issue by luigiaparicio** [redhat-cop/must-gather-operator#16]
Trying to install through OperatorHub the only option is "All namespaces on the cluster (default)"

Other option "A specific namespace on the cluster" says: This mode is not supported by this Operator

OCP version 4.6.17

**Comment by raffaelespazzoli** [comment]
this is due to a recent change in OLM. Installing in a single namespace is not supported for this operator. to install it from OLM, make sure the namespaced which you are installing to does not have any operatorgroup.

**Comment by luigiaparicio** [comment]
Any security concerns here? I mean, any user of a standard project could create a MustGather, add set additionals mustGatherImages (a custom one to damage the cluster) and that will run as cluster-admin.

**Comment by raffaelespazzoli** [comment]
one should use RBAC to determine who can create/update which CRD (MustGather in this case). OLM does not do a good job in my opinion with creating the correct roles. Not sure exactly what can be done. But for sure the direction is to create cluster level operators always.
Let me take as a TODO to see what can be done to limit the default RBAC roles that are created.

**Comment by raffaelespazzoli** [comment]
it looks to me that no role bindings are created by default. It seems that it is left to the adminstrator to grant permissions for new CRDs created by an operator. So there are no security concerns. May I close this?

**Comment by luigiaparicio** [comment]
Yes sure, thanks for the help. If I find something else I'll let you know
